#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter,OrderedDict


if __name__ == '__main__':
    s = list(input())
    for each in Counter(sorted(s)).most_common(3):
        print (*each)
